#!/usr/bin/python3
from os import system
import datetime
from time import sleep

d1 = str(datetime.datetime.now().time())

volta = 1

print('''\033[1;32m__        __   _    ____
\ \      / /__| |__/ ___|  ___ __ _ _ __  _ __   ___ _ __
 \ \ /\ / / _ \ '_ \___ \ / __/ _` | '_ \| '_ \ / _ \ '__|
  \ V  V /  __/ |_) |__) | (_| (_| | | | | | | |  __/ |
   \_/\_/ \___|_.__/____/ \___\__,_|_| |_|_| |_|\___|_|
\033[0m''')

print('\033[33m' + '\n         (Ex: www.site.com)')
try:
    site = str(input('\033[0m' + '> Site: '))
except (KeyboardInterrupt, EOFError, SystemExit):
    print('\033[91mOperação cancelada pelo usuario')
    exit()

if site == '':
    print('\033[91m[✘]' + '\nOpção Inválida')
    print('\033[0m')
    exit()

print ('\033[36m[*] Testando conexão...\033[0m')
connection = system(f'ping -c 1 -q {site} 1>/dev/null')

if connection != 0:
    print ('\033[91m[✘] Site não responde\033[0m')
    exit()
path = "/opt/webscanner/scans/"+site+'_'+d1
try:
    http = int(input('> http (1) - https (2): '))
except:
    print('\033[91m[✘] Essa entrada não pode ser nula nem uma string')
    exit()
if http != 1 and http != 2:
        print('\033[91m[✘] Selecione 1 ou 2')
        exit()

system('clear -x')

while volta == 1:

    print('\033[32m' + '(1) Whois Scan')
    print('(2) Nmap Scan')
    print('(3) Whatweb')
    print('(4) Nikto')
    print('(5) Uniscan')
    print('(6) Tudo')

    print('\033[36m')
    try:
        opcao = int(input('[*] Opção > ' + '\033[0m'))
    except (KeyboardInterrupt, EOFError, SystemExit):
        print('Operação cancelada pelo usuario')
        exit()
    if not opcao in range(1, 7):
        print('\033[91m[✘]' + '\nOpção Inválida')
        print('\033[0m')
        exit()

    print('\033[32m' + 'Deseja Salvar o resultado?')
    print('Obs,se escolher 1, o resultado só sera visivel apos a conclução do script')
    print('(1) Sim')
    print('(2) Não')

    print('\033[36m')
    try:
        save = int(input('[*] Opção > ' + '\033[0m'))
    except (KeyboardInterrupt, EOFError, SystemExit):
        print('\033[91mOperação cancelada pelo usuario')
        exit()
    if not save in range(1, 3):
        print('\033[91m[✘]' + '\nOpção Inválida')
        print('\033[0m')
        exit()
    print('\033[93mIsso pode demorar um pouco...\033[0m')

    if opcao == 1:
        if save == 1:
            system(f'echo "whois output:" >> {path}')
            system(f'\nwhois {site} >> {path}')
        else:
            system(f'\nwhois {site}')

    elif opcao == 2:
        print('\n(1) > Simples')
        print('(2) > Completo')
        nmap = int(input('\n-> \033[0m'))
        if nmap == 1:
            if save == 1:
                system(f'echo "Nmap output:" >> {path}')
                system(f'\nnmap {site} >> {path}')
            else:
                system(f'\nnmap {site}')
        elif nmap == 2:
            if save == 1:
                system(f'echo "Nmap output:" >> {path}')
                system(f'\nnmap -sV -A -O {site} >> {path}')
            else:
                system(f'\nnmap -sV -A -O {site}')

    elif opcao == 3:
        if http == 1:
            if save == 1:
                system(f'echo "Whatweb output:" >> {path}')
                system(f'\nwhatweb http://{site} >> {path}')
            else:
                system(f'\nwhatweb http://{site}')
        elif http == 2:
            if save == 1:
                system(f'echo "Whatweb output:" >> {path}')
                system(f'\nwhatweb https://{site} >> {path}')
            else:
                system(f'\nwhatweb https://{site}')

    elif opcao == 4:
        if http == 1:
            if save == 1:
                system(f'echo "Nikto output:" >> {path}')
                system(f'\nnikto -host http://{site} >> {path}')
            else:
                system(f'\nnikto -host http://{site}')            
        elif http == 2:
            if save == 1:
                system(f'echo "Nikto output:" >> {path}')
                system(f'\nnikto -host https://{site} >> {path}')
            else:
                system(f'\nnikto -host https://{site}')
            

    elif opcao == 5:
        if http == 1:
            if save == 1:
                system(f'echo "UniScan output:" >> {path}')
                system(f'\nuniscan -u http://{site} -qweds >> {path}')
            else:
                system(f'\nuniscan -u http://{site} -qweds')
        elif https == 2:
            if save == 1:
                system(f'echo "UniScan output:" >> {path}')
                system(f'\nuniscan -u https://{site} -qweds >> {path}')
            else:
                system(f'\nuniscan -u https://{site} -qweds')
            
    elif opcao == 6:
        if http == 1:
            print('\nWHOIS\n')
            if save == 1:
                system(f'echo "Whois output:" >> {path}')
                system(f'\nwhois {site} >> {path}')
            else:
                system(f'\nwhois {site}')
            

            print('\nWHATWEB\n')
            if save == 1:
                system(f'echo "Whatweb output:" >> {path}')
                system(f'\nwhatweb http://{site} >> {path}')
            else:
                system(f'\nwhatweb http://{site}')

            
            print('\n(1) > Simples')
            print('(2) > Completo')
            nmap = int(input('\n-> \033[0m'))

            if not nmap in range(1, 3):
                print('\033[91m[✘]' + '\nOpção Inválida')
                print('\033[0m')
                exit()
            
            if nmap == 1:
                print('\nNMAP (simples)\n')
                if save == 1:
                    system(f'echo "Nmap output:" >> {path}')
                    system(f'\nnmap {site} >> {path}')
                else:
                    system(f'\nnmap {site}')
                    
            elif nmap == 2:
                print('\nNMAP (completo)\n')
                if save == 1:
                    system(f'echo "Nmap output:" >> {path}')
                    system(f'\nnmap -sV -A -O {site} >> {path}')
                else:
                    system(f'\nnmap -sV -A -O {site}')


            print('\nNIKTO\n')
            if save == 1:
                system(f'echo "Nikto output:" >> {path}')
                system(f'\nnikto -host http://{site} >> {path}')
            else:
                system(f'\nnikto -host http://{site}')

            print('\nUNISCAN\n')
            if save == 1:
                system(f'echo "UniScan output:" >> {path}')
                system(f'\nuniscan -u http://{site} -qweds >> {path}')
            else:
                system(f'\nuniscan -u http://{site} -qweds')

        elif http == 2:
            print('\nWHOIS\n')
            if save == 1:
                system(f'echo "Whois output:" >> {path}')
                system(f'\nwhois {site} >> {path}')
            else:
                system(f'\nwhois {site}')
            

            print('\nWHATWEB\n')
            if save == 1:
                system(f'echo "Whatweb output:" >> {path}')
                system(f'\nwhatweb https://{site} >> {path}')
            else:
                system(f'\nwhatweb https://{site}')

            print('NMAP')
            print('\n(1) > Simples')
            print('(2) > Completo')
            nmap = int(input('\n-> \033[0m'))

            if not nmap in range(1, 3):
                print('\033[91m[✘]' + '\nOpção Inválida')
                print('\033[0m')
                exit()
            
            if nmap == 1:
                print('\nNMAP (simples)\n')
                if save == 1:
                    system(f'echo "Nmap output:" >> {path}')
                    system(f'\nnmap {site} >> {path}')
                else:
                    system(f'\nnmap {site}')
                    
            elif nmap == 2:
                print('\nNMAP (completo)\n')
                if save == 1:
                    system(f'echo "Nmap output:" >> {path}')
                    system(f'\nnmap -sV -A -O {site} >> {path}')
                else:
                    system(f'\nnmap -sV -A -O {site}')


            print('\nNIKTO\n')
            if save == 1:
                system(f'echo "Nikto output:" >> {path}')
                system(f'\nnikto -host https://{site} >> {path}')
            else:
                system(f'\nnikto -host https://{site}')

            print('\nUNISCAN\n')
            if save == 1:
                system(f'echo "UniScan output:" >> {path}')
                system(f'\nuniscan -u https://{site} -qweds >> {path}')
            else:
                system(f'\nuniscan -u https://{site} -qweds')

    volta = int(input('\033[33m' + '\nVoltar ao script (1) / Sair (0) > '))
    if save == 1:
        print(f'O resultado foi salvo em {path}')
    sleep(3)
    system('clear -x')
